//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestedToDoApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MappingTaskList
    {
        public int TaskID { get; set; }
        public string TaskName { get; set; }
        public Nullable<int> TaskStatus { get; set; }
        public Nullable<int> MappedListID { get; set; }
        public Nullable<int> MappedUserID { get; set; }
    
        public virtual MASTERUSER MASTERUSER { get; set; }
        public virtual ToDoList ToDoList { get; set; }
    }
}
