//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NestedToDoApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToDoList
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToDoList()
        {
            this.MappingTaskLists = new HashSet<MappingTaskList>();
        }
    
        public int ToDoListID { get; set; }
        public string TDName { get; set; }
        public Nullable<int> MappedUserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MappingTaskList> MappingTaskLists { get; set; }
        public virtual MASTERUSER MASTERUSER { get; set; }
    }
}
